### ISSUE TITLE
如何使用 Github 获得学长的帮助

### ISSUE THREAD

**Issue by youngdou** [sysu-swi/sysu-swi.github.io#2]
> **注：** 为了减少一些简单的、不必要的提问，培养自己解决问题的能力。请养成『先自行解决，再提问』的习惯，依照下面的顺序获取帮助

# 1. 先自己搜寻 Google/Bing/Baidu
* 我校校园网支持 Google 的搜索类业务，具体设置如下
    * 如果已经是ipv6地址，无需配置就可以使用google
    * 测试方式：http://ipv6-test.com/

![image.png | left | 293x167](https://cdn.nlark.com/yuque/0/2018/png/87305/1537155281161-8d514278-fbe7-49b2-bf99-264df5e3ccba.png "")

> - 不支持的话，请使用 ipv4 代理，参考[IPv4访问代理](https://mp.weixin.qq.com/s?__biz=MjM5MzE5MjE0MQ==&mid=2456834620&idx=2&sn=28cb03684ee3bf2e6945a9d865a2dd22&chksm=b11e339e8669ba882c7ba6bdb5db21f6c49c82dfe158f5e6428579698c9be2e20a405fd85738&mpshare=1&scene=1&srcid=0917HbFkh87HmtTu5CIy24yI#rd)
> * 相关资料
    * [IPv6助力学术科研跨越障碍](https://mp.weixin.qq.com/s?__biz=MjM5MzE5MjE0MQ==&mid=2456834537&idx=2&sn=3c715c071167e1a8d5413280cee54a84&chksm=b11e304b8669b95d17be17ddb226ef373643f338da746e0175c2dcf9e1a49b9913789e3fe1be&mpshare=1&scene=1&srcid=0917xY0BymIyOFeAozczvMhr#rd)
    * [访问Scholar学术资源的关键：是否已连接IPv6](https://mp.weixin.qq.com/s?__biz=MjM5MzE5MjE0MQ==&mid=2456834576&idx=3&sn=cab98c5d791e931f19608d30931aea0c&chksm=b11e33b28669baa4ec6ce3cb8332634768ee5762d9f0783b3b0bdbcc9ac3c541518b5e3ee928&mpshare=1&scene=1&srcid=0917WcqVPLQR01GrowlprCBs#rd)
    * [IPv4访问代理](https://mp.weixin.qq.com/s?__biz=MjM5MzE5MjE0MQ==&mid=2456834620&idx=2&sn=28cb03684ee3bf2e6945a9d865a2dd22&chksm=b11e339e8669ba882c7ba6bdb5db21f6c49c82dfe158f5e6428579698c9be2e20a405fd85738&mpshare=1&scene=1&srcid=0917HbFkh87HmtTu5CIy24yI#rd)

# 2. 和身边的同学讨论

# 3. 在 GitHub 上发起 Issue 讨论

##  3.1 在 Issue 板块发起问题，让更多同学/学长/老师看到
* 发起的 issue 将无法被github删除，请谨言慎行 ：）

![image.png | left | 771x216](https://cdn.nlark.com/yuque/0/2018/png/87305/1537155547790-782a85f3-a664-47b9-aa40-0156c60c6581.png "")

* 题目简要能说明主要问题，最好能描述情况复现的步骤，你描述得越清楚，别人越能了解问题的出现原因，从而越能及时对你提供帮助
![image.png | left | 771x413](https://cdn.nlark.com/yuque/0/2018/png/87305/1537155855595-6ac60972-12e8-4344-9bb2-e90c9ce1233d.png "")

    
##  3.2  等待他人回复
* 师兄师姐在有空的时候会及时查看issue并提供帮助
* 鼓励同学在 Issue 上回复讨论解决方案
![image.png | left | 743x489](https://cdn.nlark.com/yuque/0/2018/png/87305/1537155950819-3f955c9b-b20a-4829-ba15-fd2bbadee051.png "")

##  3.3 问题解决，关闭issue
![image.png | left | 743x701](https://cdn.nlark.com/yuque/0/2018/png/87305/1537156125398-7883c6c7-d8f3-4d9d-afad-dc7a1a4db196.png "")

##  注意！
在提出 issue 之前请确定你的问题是否已经有解决方案了
- 查看 closed 的 issues 中是否有你要的解决方案
        ![image.png | left | 715x230](https://cdn.nlark.com/yuque/0/2018/png/87305/1537156202100-be831711-9701-4f47-8a75-9c0ec58c9c1f.png "")

- 搜索
> 搜索前去掉框内的过滤说明字符，除非你知道怎么使用
![image.png | left | 687x90](https://cdn.nlark.com/yuque/0/2018/png/87305/1537156371833-01f6bfa1-30e2-45f4-9437-04e5bec42a80.png "")

![image.png | left | 687x150](https://cdn.nlark.com/yuque/0/2018/png/87305/1537156396413-553b9d85-7c85-4985-8d01-693a3fc53c30.png "")

# 4. 发邮件
如果你觉得有不适合公开讨论的问题，可以直接发邮件给对应班级的 TA 或者老师获得帮助。
[教学团队联系方式](https://sysu-swi.github.io/#%E5%9B%9B%E6%95%99%E5%AD%A6%E5%9B%A2%E9%98%9F)

**注：** 我们更鼓励使用发起 Issue 的方式解决问题 ( ´∀`)，因为你发起的 Issue 可以公开在 Github 上并保留下来，能对其他同学提供无形的帮助，提高大家的整体效率。

# 其他
[中文排版建议](https://github.com/sparanoid/chinese-copywriting-guidelines)

**Comment by xiaobaishangxian** [comment]
emmm
